version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: studyhub-db
    restart: always
    environment:
      POSTGRES_DB: studyhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./studyhub
    container_name: studyhub-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studyhub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  ai-service:
    build: ./ai-service
    container_name: studyhub-ai
    ports:
      - "8001:8001"

  frontend:
    build: ./studyhub-frontend
    container_name: studyhub-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: