services:

  postgres:
    image: postgres:15
    container_name: studyhub-db
    environment:
      POSTGRES_DB: studyhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./studyhub
    container_name: studyhub-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - ai-service   # 👈 add this
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studyhub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AI_SERVICE_URL: http://ai-service:8001   # 👈 add this

  ai-service:
    build: ./ai-service
    container_name: studyhub-ai
    ports:
      - "8001:8001"

  frontend:
    build: ./studyhub-frontend
    container_name: studyhub-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend